# Generated by Django 3.1.2 on 2020-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course',
            name='quater',
            field=models.CharField(choices=[('QUATER1', 'QUATER1'), ('QUATER2', 'QUATER2'), ('QUATER3', 'QUATER3')], default='QUATER1', max_length=10),
            preserve_default=False,
        ),
    ]
