# Generated by Django 3.1.2 on 2020-11-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20201120_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
