# Generated by Django 3.1.2 on 2020-12-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_classe_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
