# Generated by Django 3.1.2 on 2020-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_course_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo',
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
