# Generated by Django 3.1.2 on 2020-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20201211_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clasee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
