# Generated by Django 3.1.2 on 2020-12-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_clasee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clasee',
        ),
    ]
