# Generated by Django 3.1.2 on 2020-12-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_student_clasee'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='profile_pc',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
