# Generated by Django 3.1.2 on 2020-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_school_profile_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='profile_pc',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
