# Generated by Django 3.1.2 on 2020-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_sector_profile_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='profile_pc',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
