# Generated by Django 3.1.2 on 2021-01-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20201218_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='physical_disability',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=15),
        ),
    ]
