# Generated by Django 3.1.2 on 2021-01-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_student_physical_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
