# Generated by Django 3.1.2 on 2021-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20210116_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='profile_pc',
            field=models.ImageField(blank=True, default='anonymous-user.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='profile_pc',
            field=models.ImageField(blank=True, default='anonymous-user.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sector',
            name='profile_pc',
            field=models.ImageField(blank=True, default='anonymous-user.png', null=True, upload_to=''),
        ),
    ]
