# Generated by Django 3.1.2 on 2021-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210303_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_reg',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
