# Generated by Django 3.1.2 on 2021-04-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20210422_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_reg',
            field=models.IntegerField(),
        ),
    ]
